In [ ]:
# 1. Data Loading

import pandas as pd

df = pd.read_csv("../data/raw_data/vehicle_sales_raw.csv")

df.head()

,Date,Salesperson,Customer Name,Customer Age,Customer Gender,Car Make,Car Model,Car Year,Quantity,Sale Price,...,Discount,Payment Method,Commission Rate,Commission Earned,Sales Region,Sale Year,Sale Month,Sale Quarter,Day of Week,Season
0,2019-04-02,Mary Simon,Kristin Blackwell,42,Male,Hyundai,Santa Fe,2019,1,25949.00,...,0.05,Loan,0.07,1816.43,Alaska,2019,April,2,Tuesday,Spring
1,2018-04-13,Nancy Mercado,Diana Black,65,Female,Ford,Explorer,2021,2,82236.84,...,0.02,Cash,0.05,4111.84,Alabama,2023,April,2,Friday,Spring
2,2021-01-31,Pamela King,Craig Powers,67,Female,Kia,Telluride,2023,2,60810.48,...,0.01,Lease,0.06,0.00,South Carolina,2024,January,1,Sunday,Winter
3,2020-09-30,Elizabeth Ashley,Jade Williams,69,Female,BMW,5 Series,2022,2,154746.56,...,0.04,Lease,0.06,9284.79,Maryland,2024,September,3,Wednesday,Fall
4,2020-07-03,Brian Cline,Nicholas Fernandez,50,Male,Audi,A6,2019,1,48629.00,...,0.06,Loan,0.09,4376.61,Colorado,2019,July,3,Friday,Summer

In [11]:
df.shape

(1000668, 22)

In [12]:
print(df.columns)

Index(['Date', 'Salesperson', 'Customer Name', 'Customer Age',
       'Customer Gender', 'Car Make', 'Car Model', 'Car Year', 'Quantity',
       'Sale Price', 'Cost', 'Profit', 'Discount', 'Payment Method',
       'Commission Rate', 'Commission Earned', 'Sales Region', 'Sale Year',
       'Sale Month', 'Sale Quarter', 'Day of Week', 'Season'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000668 entries, 0 to 1000667
Data columns (total 22 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Date               1000668 non-null  object
 1   Salesperson        1000668 non-null  object
 2   Customer Name      1000668 non-null  object
 3   Customer Age       1000668 non-null  int64
 4   Customer Gender    1000668 non-null  object
 5   Car Make           1000668 non-null  object
 6   Car Model          1000668 non-null  object
 7   Car Year           1000668 non-null  int64
 8   Quantity           1000668 non-null  int64
 9   Sale Price         1000668 non-null  float64
 10  Cost               1000668 non-null  float64
 11  Profit             1000668 non-null  float64
 12  Discount           1000668 non-null  float64
 13  Payment Method     1000668 non-null  object
 14  Commission Rate    1000668 non-null  float64
 15  Commission Earned  1000668 non-null  float64
 16  Sales Region       1000668 non-null  object
 17  Sale Year          1000668 non-null  int64
 18  Sale Month         1000668 non-null  object
 19  Sale Quarter       1000668 non-null  int64
 20  Day of Week        1000668 non-null  object
 21  Season             1000668 non-null  object
dtypes: float64(6), int64(5), object(11)
memory usage: 168.0+ MB

In [ ]:
# 2. Data Cleaning
print(df.isnull().sum())
print(df.duplicated().sum())

Date                 0
Salesperson          0
Customer Name        0
Customer Age         0
Customer Gender      0
Car Make             0
Car Model            0
Car Year             0
Quantity             0
Sale Price           0
Cost                 0
Profit               0
Discount             0
Payment Method       0
Commission Rate      0
Commission Earned    0
Sales Region         0
Sale Year            0
Sale Month           0
Sale Quarter         0
Day of Week          0
Season               0
dtype: int64
0

In [16]:
df.describe()

,Customer Age,Car Year,Quantity,Sale Price,Cost,Profit,Discount,Commission Rate,Commission Earned,Sale Year,Sale Quarter
count,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06,1.000668e+06
mean,4.502699e+01,2.020998e+03,2.120985e+00,8.664273e+04,7.268286e+04,1.395987e+04,5.998358e-02,7.118896e-02,5.607642e+03,2.022020e+03,2.508652e+00
std,1.472792e+01,1.999433e+00,6.081103e-01,1.724110e+05,3.632967e+05,2.130789e+05,3.756358e-02,1.744452e-02,3.577184e+03,1.773736e+00,1.118128e+00
min,2.000000e+01,2.018000e+03,1.000000e+00,9.508000e+03,6.969890e+03,-1.499900e+07,0.000000e+00,3.000000e-02,0.000000e+00,2.018000e+03,1.000000e+00
25%,3.200000e+01,2.019000e+03,2.000000e+00,5.496180e+04,4.364586e+04,8.204370e+03,3.000000e-02,6.000000e-02,3.286540e+03,2.021000e+03,2.000000e+00
50%,4.500000e+01,2.021000e+03,2.000000e+00,7.390822e+04,5.932850e+04,1.566558e+04,6.000000e-02,7.000000e-02,4.988250e+03,2.022000e+03,3.000000e+00
75%,5.800000e+01,2.023000e+03,3.000000e+00,1.072945e+05,8.300239e+04,2.579275e+04,9.000000e-02,8.000000e-02,7.412760e+03,2.024000e+03,4.000000e+00
max,7.000000e+01,2.024000e+03,3.000000e+00,2.821159e+07,4.139586e+07,9.047493e+04,1.500000e-01,1.200000e-01,3.438490e+04,2.024000e+03,4.000000e+00

In [18]:
df.dtypes

Date                  object
Salesperson           object
Customer Name         object
Customer Age           int64
Customer Gender       object
Car Make              object
Car Model             object
Car Year               int64
Quantity               int64
Sale Price           float64
Cost                 float64
Profit               float64
Discount             float64
Payment Method        object
Commission Rate      float64
Commission Earned    float64
Sales Region          object
Sale Year              int64
Sale Month            object
Sale Quarter           int64
Day of Week           object
Season                object
dtype: object

In [ ]:
# 3. Exploratory Data Analysis
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Date                 datetime64[ns]
Salesperson                  object
Customer Name                object
Customer Age                  int64
Customer Gender              object
Car Make                     object
Car Model                    object
Car Year                      int64
Quantity                      int64
Sale Price                  float64
Cost                        float64
Profit                      float64
Discount                    float64
Payment Method               object
Commission Rate             float64
Commission Earned           float64
Sales Region                 object
Sale Year                     int64
Sale Month                   object
Sale Quarter                  int64
Day of Week                  object
Season                       object
dtype: object

In [22]:
# profit margine %
df["Profit Margine"] = df["Profit"]/df["Sale Price"]*100
#sales values
df["Sales Value"] = df["Quantity"]* df["Sale Price"]
# cost values
df["Cost Value"]  = df["Quantity"]*df["Cost"]
df.head()

,Date,Salesperson,Customer Name,Customer Age,Customer Gender,Car Make,Car Model,Car Year,Quantity,Sale Price,...,Commission Earned,Sales Region,Sale Year,Sale Month,Sale Quarter,Day of Week,Season,Profit Margine,Sales Value,Cost Value
0,2019-04-02,Mary Simon,Kristin Blackwell,42,Male,Hyundai,Santa Fe,2019,1,25949.00,...,1816.43,Alaska,2019,April,2,Tuesday,Spring,14.688235,25949.00,22137.55
1,2018-04-13,Nancy Mercado,Diana Black,65,Female,Ford,Explorer,2021,2,82236.84,...,4111.84,Alabama,2023,April,2,Friday,Spring,24.454150,164473.68,124253.04
2,2021-01-31,Pamela King,Craig Powers,67,Female,Kia,Telluride,2023,2,60810.48,...,0.00,South Carolina,2024,January,1,Sunday,Winter,-14.283952,121620.96,138993.24
3,2020-09-30,Elizabeth Ashley,Jade Williams,69,Female,BMW,5 Series,2022,2,154746.56,...,9284.79,Maryland,2024,September,3,Wednesday,Fall,25.041255,309493.12,231992.16
4,2020-07-03,Brian Cline,Nicholas Fernandez,50,Male,Audi,A6,2019,1,48629.00,...,4376.61,Colorado,2019,July,3,Friday,Summer,21.473545,48629.00,38186.63

In [24]:
print(df["Car Make"].unique())
print(df["Car Model"].unique())
print(df["Season"].unique())

['Hyundai' 'Ford' 'Kia' 'BMW' 'Audi' 'Nissan' 'Toyota' 'Chevrolet'
 'Mercedes' 'Honda']
['Santa Fe' 'Explorer' 'Telluride' '5 Series' 'A6' 'A4' 'Pathfinder'
 'Escape' 'Highlander' 'Tucson' 'Tahoe' 'C-Class' 'Altima' 'Accord'
 'Maxima' 'F-150' 'Q5' 'Prius' 'A8' 'RAV4' 'Sonata' 'Camry' 'Kona'
 'Sorento' 'Elantra' 'Rogue' 'Equinox' 'Q7' 'Sportage' 'CR-V' 'Sentra'
 'Pilot' 'E-Class' 'GLC' 'GLE' 'Optima' 'Odyssey' 'Mustang' 'X3' 'Forte'
 '7 Series' '3 Series' 'Silverado' 'Corolla' 'S-Class' 'Civic' 'Focus'
 'Malibu' 'Camaro' 'X5']
['Spring' 'Winter' 'Fall' 'Summer']

In [ ]:
# 4. Final Insights
df.to_csv("../data/cleaned_data/vehicle_sales_cleaned.csv", index=False)